---
title: "Final Project"
author: "s3637387, Rupesh Papneja"
date: "2 September 2017"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Loading required libraries

```{r echo=TRUE, include=TRUE, message=FALSE, warning=FALSE}
library(easypackages)
libs <- c("forecast","expsmooth","TSA","knitr","tseries", "gglot2", "readxl",
          "dynlm","Hmisc","car","AER", "magrittr","tseries", "dLagM",
          "stats", "x12")
libraries(libs)

```
## Defining the class objects and method to process each row

```{r}

setClass(Class="TClass",
         representation(
           type="character",
           frequency="numeric",
           id="numeric",
           n="numeric", 
           diff_n="numeric",
           forecast_period="numeric",
           category="character",
           start_year="numeric",
           start_frequency="numeric",
           superposition="numeric",
           original_data="numeric",
           validation="numeric",
           ts_complete="ts",
           ts_training="ts",
           models_df="data.frame"
      )
)

setClass(Class="RClass",
         representation(
           key="character",
           mase="numeric",
           aic="numeric",
           bic="numeric", 
           aicc="numeric",
           swtest.pvalue="numeric", # check shapiro-wilk test value
           swtest.count="numeric",
           boxtest.pvalue="numeric",
           boxtest.count="numeric",
           ts_forecast="ts" # forecast time series
         )
)

calculateMASE <- function(validationSet,forecastSet){
  nlen = length(validationSet)
  error.terms = validationSet - forecastSet
  esum = 0 
  for (i in 2:nlen){
    esum = esum + abs(forecastSet[i] - forecastSet[i-1] )
  }
  if (esum == 0) {
    esum = 0.0001 # code to avoid division by zero error
  }
  q.t = error.terms / (esum/(nlen-1))
  rm(nlen)
  rm(esum)
  rm(error.terms)
  return (mean(abs(q.t)))
}

checkShapiroWilkResiduals <- function(residuals){
  sw.test <- shapiro.test(residuals)
  pval <- sw.test$p.value
  ct <- 0
  if(pval < 0.05) {
    ct <- sum((residuals > 0.05) == TRUE) + sum((residuals < -0.05) == TRUE)
  }
  rm(sw.test)
  return (c(pval,ct))
}

checkBoxTestResiduals <- function(residuals){
  box.test <- Box.test(residuals, lag = 1, type = "Ljung-Box", fitdf = 0)
  pval_box <- box.test$p.value
  ct_box <- 0
  if(pval_box < 0.05) {
    ct_box <- sum((residuals > 0.05) == TRUE) + sum((residuals < -0.05) == TRUE)
  }
  rm(box.test)
  return (c(pval_box,ct_box))
}

processDataRow <- function(x, series_frequency, type) {
  
  id <- as.integer(x[1])
  n <- as.integer(x[2])
  forecast_period <- as.integer(x[3])
  category <- x[4]
  start_year <- as.integer(x[5])
  start_frequency <- as.integer(x[6])
  start_n <- 7
  
  vec <- as.vector(as.numeric(x[seq(from = start_n, to = n + start_n - 1)]))
  
  #checking for minimum value and calculating value that is to be added to time series object when negative.
  
  min_x <- min(vec)
  superposition <- ifelse(min_x > 0,0,(min_x * -1 + 0.1))
  
  diff_n <- as.integer(n * .05)
  
  diff_n <- ifelse(diff_n == 1,2,diff_n)
  
  vec_2 <- as.vector(as.numeric(x[seq(from = start_n, to = n + start_n - diff_n - 1)])) # change formula for training set if required
  
  vec_3 <- as.vector(as.numeric(x[seq(from = start_n + n - diff_n, to = start_n + n - 1)]))
  
  ts_complete <- ts(vec,start = c(start_year,start_frequency),frequency=series_frequency)
  ts_training <- ts(vec_2,start = c(start_year,start_frequency),frequency=series_frequency)
  
  
  return (new("TClass",type=type,
              frequency=series_frequency,
              id=id,
              n=n,
              diff_n=diff_n,
              forecast_period=forecast_period,
              category=category,
              start_year=start_year,
              start_frequency=start_frequency,
              superposition=superposition,
              original_data=vec,
              validation=vec_3,
              ts_complete=ts_complete,
              ts_training=ts_training)
  )
}

getType <- function(sheetNumber) {
  if (sheetNumber == 1) "Y"
  else if (sheetNumber == 2) "Q"
  else if (sheetNumber == 3) "M"
}

getFrequency <- function(sheetNumber) {
  if (sheetNumber == 1) 1
  else if (sheetNumber == 2) 4
  else if (sheetNumber == 3) 12
}

getMethodName <- function(m) {
  st <- substring(text = m,5)
  st <- substring(text = st,1, nchar(st) - 1)
  st <- gsub(",","",st)
}

getAutoModels <- function(tsobject, forecasting_period) {
  lst <- list()
  ics <- c("bic", "aicc", "aic")
  dampeds <- c(TRUE, FALSE)
  xg <- expand.grid(ics,dampeds)
  for(i in 1:6){
    fit.auto <- ets(tsobject,model="ZZZ", damped = xg[i,2], ic=toString(xg[i,1]))
    k <- ifelse(xg[i,2],paste("ETS_AUTO",toString(xg[i,1]),"damped", sep='_'),paste("ETS_AUTO",toString(xg[i,1]), sep="_"))
    frc.ets <- forecast(fit.auto,h=forecasting_period)
    vec_sw <- checkShapiroWilkResiduals(fit.auto$residuals)
    vec_box <- checkBoxTestResiduals(fit.auto$residuals)
    lst[[k]] <- new("RClass",key=k,
              mase=accuracy(fit.auto)[6],
              aic=fit.auto$aic,
              bic=fit.auto$bic,
              aicc=fit.auto$aicc,
              swtest.pvalue=vec_sw[1],
              swtest.count=vec_sw[2],
              boxtest.pvalue=vec_box[1],
              boxtest.count=vec_box[2],
              ts_forecast=frc.ets$mean)
    rm(frc.ets)
    rm(k)
    rm(fit.auto)
    rm(vec_sw)
    rm(vec_box)
  }
  rm(i)
  rm(ics)
  rm(dampeds)
  rm(xg)
  return (lst)
}

getSesModels <- function(tsobject, forecasting_period) {
  lst <- list()
  initials <- c("simple", "optimal")
  exponentials <- c(TRUE, FALSE)
  dampeds <- c(TRUE, FALSE)
  xg <- expand.grid(initials,dampeds,exponentials)
  for(i in 1:8){
    k <- paste('ses',toString(xg[i,1]),ifelse(xg[i,2],'d',''),ifelse(xg[i,3],'x',''),sep='')
    tryCatch({
      fit.ses <- ses(tsobject,initial=toString(xg[i,1]), damped=xg[i,2], exponential=xg[i,3], h=forecasting_period)
      vec_sw <- checkShapiroWilkResiduals(fit.ses$residuals)
      vec_box <- checkBoxTestResiduals(fit.ses$residuals)
      lst[[k]] <- new("RClass",key=k,
              mase=accuracy(fit.ses)[6],
              aic=ifelse(is.null(fit.ses$model$aic),-1,fit.ses$model$aic),
              bic=ifelse(is.null(fit.ses$model$bic),-1,fit.ses$model$bic),
              aicc=ifelse(is.null(fit.ses$model$aicc),-1,fit.ses$model$aicc),
              swtest.pvalue=vec_sw[1],
              swtest.count=vec_sw[2],
              boxtest.pvalue=vec_box[1],
              boxtest.count=vec_box[2],
              ts_forecast=fit.ses$mean
              )
      rm(fit.ses)
      rm(vec_sw)
      rm(vec_box)
    },error=function(e){
      print(paste(k,e,sep=":"))
    })
    rm(k)
  }
  rm(i)
  rm(initials)
  rm(dampeds)
  rm(exponentials)
  rm(xg)
  return (lst)
}

getHoltModels <- function(tsobject, forecasting_period){
  lst <- list()
  initials <- c("simple", "optimal")
  exponentials <- c(TRUE, FALSE)
  dampeds <- c(TRUE, FALSE)
  xg <- expand.grid(initials,dampeds,exponentials)
  for(i in 1:8){
    if((xg[i,1] == "simple" && xg[i,2]==FALSE) || (xg[i,1] == "optimal")) {
      k <- paste('holt',toString(xg[i,1]),ifelse(xg[i,2],'d',''),ifelse(xg[i,3],'x',''),sep='')
      tryCatch({
        fit.holt <- holt(tsobject, initial=toString(xg[i,1]), damped=xg[i,2], exponential=xg[i,3], h=forecasting_period)
        vec_sw <- checkShapiroWilkResiduals(fit.holt$residuals)
        vec_box <- checkBoxTestResiduals(fit.holt$residuals)
        lst[[k]] <- new("RClass",key=k,
                mase=accuracy(fit.holt)[6],
                aic=ifelse(is.null(fit.holt$model$aic),-1,fit.holt$model$aic),
                bic=ifelse(is.null(fit.holt$model$bic),-1,fit.holt$model$bic),
                aicc=ifelse(is.null(fit.holt$model$aicc),-1,fit.holt$model$aicc),
                swtest.pvalue=vec_sw[1],
                swtest.count=vec_sw[2],
                boxtest.pvalue=vec_box[1],
                boxtest.count=vec_box[2],
                ts_forecast=fit.holt$mean
                )
        rm(vec_sw)
        rm(vec_box)
        rm(fit.holt)
      },error=function(e){
        print(paste(k,e,sep=":"))
      })
      rm(k)
    }
  }
  rm(i)
  rm(initials)
  rm(dampeds)
  rm(exponentials)
  rm(xg)
  return (lst)
}

getHoltWintersModels <- function(tsobject, forecasting_period){
  lst <- list()
  seasonals <- c("additive", "multiplicative")
  exponentials <- c(TRUE, FALSE)
  dampeds <- c(TRUE, FALSE)
  xg <- expand.grid(seasonals,dampeds,exponentials)
  for(i in 1:8){
    k <- paste('hw',toString(xg[i,1]),ifelse(xg[i,2],'d',''),ifelse(xg[i,3],'x',''),sep='')
    tryCatch({
      fit.hw <- hw(tsobject,seasonal=toString(xg[i,1]), damped=xg[i,2], exponential=xg[i,3], h=forecasting_period)
      vec_sw <- checkShapiroWilkResiduals(fit.hw$residuals)
      vec_box <- checkBoxTestResiduals(fit.hw$residuals)
      lst[[k]] <- new("RClass",key=k,
              mase=accuracy(fit.hw)[6],
              aic=ifelse(is.null(fit.hw$model$aic),-1,fit.hw$model$aic),
              bic=ifelse(is.null(fit.hw$model$bic),-1,fit.hw$model$bic),
              aicc=ifelse(is.null(fit.hw$model$aicc),-1,fit.hw$model$aicc),
              swtest.pvalue=vec_sw[1],
              swtest.count=vec_sw[2],
              boxtest.pvalue=vec_box[1],
              boxtest.count=vec_box[2],
              ts_forecast=fit.hw$mean)
      rm(fit.hw)
      rm(vec_box)
      rm(vec_sw)
    },error=function(e){
      print(paste(k,e,sep=":"))
    })
    rm(k)
  }
  rm(i)
  rm(seasonals)
  rm(dampeds)
  rm(exponentials)
  rm(xg)
  return (lst)
}

getEtsModels <- function(tsobject, forecasting_period){
  lst <- list()
  e <- c("A","M","N")
  t <- c("A","M","N")
  s <- c("A","M","N")
  dampeds <- c(TRUE, FALSE)
  xg <- expand.grid(e,t,s,dampeds)
  for(i in 1:54){
    mt <- toString(paste(xg[i,1],xg[i,2],xg[i,3],sep = ""))
    k <- paste('ETS(',mt,ifelse(xg[i,4],'d',''),')',sep='')
    tryCatch({
      if(mt == "NNN") {
        fit.ets <- ets(tsobject, damped = xg[i,4])
        frc.ets <- forecast(fit.ets,h=forecasting_period)
        vec_sw <- checkShapiroWilkResiduals(fit.ets$residuals)
        vec_box <- checkBoxTestResiduals(fit.ets$residuals)
        lst[[k]] <- new("RClass",key=k,
              mase=accuracy(fit.ets)[6],
              aic=fit.ets$aic,
              bic=fit.ets$bic,
              aicc=fit.ets$aicc,
              swtest.pvalue=vec_sw[1],
              swtest.count=vec_sw[2],
              boxtest.pvalue=vec_box[1],
              boxtest.count=vec_box[2],
              ts_forecast=frc.ets$mean)
        rm(frc.ets)
        rm(fit.ets)
        rm(vec_sw)
        rm(vec_box)
      } else if(xg[i,1] != "N") {
        if(xg[i,3] != "N") {
          if(frequency(tsobject) != 1) {
            fit.ets <- ets(tsobject, model=mt, damped=xg[i,4])
            frc.ets <- forecast(fit.ets,h=forecasting_period)
            vec_sw <- checkShapiroWilkResiduals(fit.ets$residuals)
            vec_box <- checkBoxTestResiduals(fit.ets$residuals)
            lst[[k]] <- new("RClass",key=k,
                mase=accuracy(fit.ets)[6],
                aic=fit.ets$aic,
                bic=fit.ets$bic,
                aicc=fit.ets$aicc,
                swtest.pvalue=vec_sw[1],
                swtest.count=vec_sw[2],
                boxtest.pvalue=vec_box[1],
                boxtest.count=vec_box[2],
                ts_forecast=frc.ets$mean)
            rm(frc.ets)
            rm(fit.ets)
            rm(vec_sw)
            rm(vec_box)
          }
        } else {
          fit.ets <- ets(tsobject, model=mt, damped=xg[i,4])
          frc.ets <- forecast(fit.ets,h=forecasting_period)
          vec_sw <- checkShapiroWilkResiduals(fit.ets$residuals)
          vec_box <- checkBoxTestResiduals(fit.ets$residuals)
          lst[[k]] <- new("RClass",key=k,
                mase=accuracy(fit.ets)[6],
                aic=fit.ets$aic,
                bic=fit.ets$bic,
                aicc=fit.ets$aicc,
                swtest.pvalue=vec_sw[1],
                swtest.count=vec_sw[2],
                boxtest.pvalue=vec_box[1],
                boxtest.count=vec_box[2],
                ts_forecast=frc.ets$mean)
          rm(frc.ets)
          rm(fit.ets)
          rm(vec_sw)
          rm(vec_box)
        }
      }
    },error=function(e){
      print(paste(k,e,sep=":"))
    })
    rm(k)
    rm(mt)
  }
  rm(i)
  rm(e)
  rm(t)
  rm(s)
  rm(dampeds)
  rm(xg)
  return (lst)
}

```

# function to try all models in time series object

```{r}
getAllModelsMase <- function(tsobject, forecasting_period) {
  maselst <- list()
  maselst <- append(maselst,getAutoModels(tsobject, forecasting_period))
  maselst <- append(maselst,getSesModels(tsobject, forecasting_period))
  maselst <- append(maselst,getHoltModels(tsobject, forecasting_period))
  if(frequency(tsobject) != 1) {
    maselst <- append(maselst,getHoltWintersModels(tsobject, forecasting_period))
  }
  maselst <- append(maselst,getEtsModels(tsobject, forecasting_period))
  return (maselst)
}
```

## Reading all data and processing it to create time series objects and output list of class objects containing details

```{r}
all_objects <- list()
for(i in c(1,2,3)) {
  df <- read_excel(path="./data/M3C_reduced.xlsx" , sheet=i, trim_ws=TRUE)
  output <- apply(df,1,processDataRow,getFrequency(i),getType(i))
  all_objects <- append(all_objects,output)
  rm(df)
  rm(output)
}
rm(i)
```


```{r echo=TRUE, include=FALSE, message=FALSE, warning=FALSE}
modelsSpecs <- list()
len <- length(all_objects)
for(il in 1:len) {
  element <- all_objects[[il]]
  print(all_objects[[il]]@id)
  modelsSpecs[[all_objects[[il]]@id]] <- getAllModelsMase(element@ts_training, element@forecast_period) 
}
rm(il)
rm(element)
```

#create a data frame for sorting
```{r}
result_df <- data.frame(id=numeric(),
                        type=character(),
                        frequency=numeric(),
                        category=character(),
                        key=character(),
                        mase=numeric(),
                        aic=numeric(),
                        aicc=numeric(),
                        bic=numeric(),
                        swtest.pvalue=numeric(),
                        swtest.count=numeric(),
                        boxtest.pvalue=numeric(),
                        boxtest.count=numeric(),
                        forecase.mase=numeric())
names_vec<-c("id",
                    "type",
                    "frequency",
                    "category",
                    "modelKey",
                    "mase",
                    "aic",
                    "aicc",
                    "bic",
                    "sw.pvalue",
                    "sw.count",
                    "box.pvalue",
                    "box.count",
                    "forecase.mase")
names(result_df) <- names_vec
for(il in 1:len) {
  lst <-  modelsSpecs[[all_objects[[il]]@id]]
  df <- data.frame(id=numeric(),
                   type=character(),
                   frequency=numeric(),
                   category=character(),
                   key=character(),
                   mase=numeric(),
                   aic=numeric(),
                   aicc=numeric(),
                   bic=numeric(),
                   swtest.pvalue=numeric(),
                   swtest.count=numeric(),
                   boxtest.pvalue=numeric(),
                   boxtest.count=numeric(),
                   forecase.mase=numeric())
  names(df)<-names_vec
  for (loop  in 1:length(lst)){
    vc <- as.vector(lst[[loop]]@ts_forecast)
    vc <- vc[1:length(all_objects[[il]]@validation)]
    temp <- data.frame(all_objects[[il]]@id,
                       all_objects[[il]]@type,
                       all_objects[[il]]@frequency,
                       all_objects[[il]]@category,
                       lst[[loop]]@key,
                       lst[[loop]]@mase,
                       lst[[loop]]@aic,
                       lst[[loop]]@aicc,
                       lst[[loop]]@bic,
                       lst[[loop]]@swtest.pvalue,
                       lst[[loop]]@swtest.count,
                       lst[[loop]]@boxtest.pvalue,
                       lst[[loop]]@boxtest.count,
                       calculateMASE(all_objects[[il]]@validation,vc))
    names(temp)<-names_vec
    df <- rbind(df,temp)
    rm(temp)
    rm(vc)
  }
  df <- df[with(df, order(mase)), ]
  # Adding data frame for future reporting purpose
  all_objects[[il]]@models_df <- df
  #Selection logic for best model needs to go here
  result_df <- rbind(result_df,df[1,])
  rm(df)
  rm(lst)
}
rm(il)
rm(loop)
rm(names_vec)
```

